version: '3.8'

services:
  backend:
    build: ./backend
    container_name: absas-backend-1
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Keeps your SQLite file safe on your host computer
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/app  # 👈 CHANGED THIS BACK to target your inner directory!